### ISSUE TITLE
NNBD migration

### ISSUE THREAD

**Issue by amake** [git-touch/highlight#18]
Are there any plans to migrate these packages to non-nullable-by-default?

**Comment by IchordeDionysos** [comment]
@pd4d10 would appreciate if you would add null safety support 👍 

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

**Comment by IchordeDionysos** [comment]
The new Dart version with null-safety was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by WieFel** [comment]
Waiting for this package to be null-safe too

**Comment by pd4d10** [comment]
Landed in the latest v0.7.0
